server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: FoodOrderingApp-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-233-55-123.compute-1.amazonaws.com:5432/dcagjd5dkoundv
    username: lppkeoozbrqybt
    password: a0db7eb6924400649ae09ad669b149873f94fa68571b2198c469351d9a3a2cda

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect